Repository diwako/diwako_dui, pull requests merged in 2020-05, with the labels that each got.

#128 Linter update
  .editorconfig
  .github/workflows/main.yml
  addons/buddy/XEH_postInit.sqf
  addons/main/XEH_preInit.sqf
  addons/main/include/getColorStyles.sqf
  addons/radar/XEH_preInit.sqf
  circle.yml
  tools/sqf_linter_LogChecker.py
Labels: ignore_changelog

#130 Show icon when speaking
  addons/main/CfgIconStyles.hpp
  addons/main/include/getIconStyles.sqf
  addons/main/script_version.hpp
  addons/main/stringtable.xml
  addons/radar/XEH_preInit.sqf
  addons/radar/functions/fnc_cacheLoop.sqf
  addons/radar/functions/fnc_displayUnitOnCompass.sqf
Labels: enhancement

#126 Adds missing russian translations
  addons/main/stringtable.xml
Labels: enhancement

#129 Allow all items which can be used as compass
  addons/radar/XEH_preInit.sqf
  addons/radar/functions/fnc_getCompass.sqf
Labels: enhancement

#125 dont run GUI updates while game is paused or minimized
  addons/radar/XEH_PREP.hpp
  addons/radar/functions/fnc_compass.sqf
  addons/radar/functions/fnc_compassPFH.sqf
  addons/radar/functions/fnc_syncGroups.sqf
  addons/radar/functions/fnc_syncGroupsPFH.sqf
Labels: enhancement

#131 Fixes for isSpeaking integration after testing
  addons/radar/XEH_preInit.sqf
  addons/radar/functions/fnc_compassPFH.sqf
  addons/radar/functions/fnc_displayUnitOnCompass.sqf
  addons/radar/functions/fnc_getIcon.sqf
  addons/radar/functions/fnc_incomingFinger.sqf
  tools/sqf_linter_LogChecker.py
Labels: enhancement, ignore_changelog

#127 Crew radar
  addons/indicators/XEH_preInit.sqf
  addons/indicators/functions/fnc_display.sqf
  addons/indicators/stringtable.xml
  addons/main/XEH_PREP.hpp
  addons/main/functions/fnc_isInCrew.sqf
  addons/main/stringtable.xml
  addons/radar/XEH_preInit.sqf
  addons/radar/functions/fnc_displayUnitOnCompass.sqf
  addons/radar/script_component.hpp
  authors.txt
Labels: enhancement

#132 Adds russian translation for speaking icon feature
  addons/main/stringtable.xml
Labels: enhancement

#135 Add ability to hide cardinal points even with compass
  addons/main/stringtable.xml
  addons/radar/XEH_preInit.sqf
  addons/radar/functions/fnc_cacheLoop.sqf
Labels: enhancement
