Repository diwako/diwako_dui, pull requests merged in 2021-04, with the labels that each got.

#172 Add LIS for Nametags to see names inside and outside the Vehicle
  addons/nametags/config.cpp
  addons/nametags/functions/fnc_calculateFadeValue.sqf
  addons/nametags/functions/fnc_onDraw.sqf
  addons/nametags/settings.sqf
  addons/nametags/stringtable.xml
Labels: enhancement

#167 add tfar 0.9.12 compatibility
  addons/main/XEH_preInit.sqf
  addons/radar/XEH_postInit.sqf
  addons/radar/XEH_preInit.sqf
  tools/sqf_linter_LogChecker.py
Labels: enhancement

#179 Use VIEW lod in Nametags
  addons/nametags/functions/fnc_onDraw.sqf
Labels: enhancement

#181 add automatic translation progression tracker
  .github/workflows/main.yml
  tools/stringtableDeploy.py
  tools/stringtablediag.py
Labels: enhancement

#180 Increase Proiority of Medic, Engineer and EOD for Icons
  addons/radar/functions/fnc_getIcon.sqf
Labels: enhancement

#183 Nametags - Fix not showing UAVs with names
  addons/nametags/functions/fnc_onDraw.sqf
Labels: bug

#185 Nametags - use fire instead of view for lineIntersectsSurfaces
  addons/nametags/functions/fnc_onDraw.sqf
Labels: bug

#182 Radar - Fix speaking icon being stuck
  README.md
  addons/buddy/XEH_postInit.sqf
  addons/main/script_version.hpp
  addons/radar/XEH_postInit.sqf
  addons/radar/XEH_preInit.sqf
  addons/radar/functions/fnc_getCompass.sqf
  addons/radar/functions/fnc_incomingFinger.sqf
  addons/radar/functions/fnc_sortNameList.sqf
Labels: bug

#184 compile sqf scripts to bytecode before packaging
  .gitignore
  addons/indicators/include/getIndicatorStyles.sqf
  addons/main/include/getColorStyles.sqf
  addons/main/include/getIconStyles.sqf
  addons/main/script_mod.hpp
  addons/main/script_version.hpp
  addons/nametags/settings.sqf
  addons/radar/include/getPointerStyles.sqf
  hemtt.toml
  sqfc.json
Labels: ignore_changelog

#187 Update Japanese translation
  addons/indicators/stringtable.xml
  addons/main/stringtable.xml
  addons/nametags/stringtable.xml
Labels: enhancement
