Repository diwako/diwako_dui, pull requests merged in 2021-03, with the labels that each got.

#162 Nametags - Don't show on uav
  addons/nametags/functions/fnc_onDraw.sqf
Labels: bug

#170 Nametags: Custom Group
  addons/nametags/functions/fnc_cacheLoop.sqf
Labels: enhancement

#169 improve spectator detection
  addons/main/functions/fnc_canHudBeShown.sqf
Labels: enhancement

#157 Use isNotEqualTo
  .github/workflows/main.yml
  addons/buddy/XEH_postInit.sqf
  addons/indicators/functions/fnc_display.sqf
  addons/main/XEH_preInit.sqf
  addons/main/functions/fnc_cacheLoop.sqf
  addons/main/functions/fnc_isInCrew.sqf
  addons/nametags/XEH_postInit.sqf
  addons/nametags/functions/fnc_cacheLoop.sqf
  addons/nametags/functions/fnc_handleInitPost.sqf
  addons/nametags/functions/fnc_onDraw.sqf
  addons/radar/functions/fnc_cacheLoop.sqf
  addons/radar/functions/fnc_compassPFH.sqf
  addons/radar/functions/fnc_displayUnitOnCompass.sqf
  addons/radar/functions/fnc_getCompass.sqf
  addons/radar/functions/fnc_getIcon.sqf
  addons/radar/functions/fnc_incomingFinger.sqf
  addons/radar/functions/fnc_syncGroupsPFH.sqf
  tools/sqf_validator.py
Labels: enhancement

#173 Fix ACE EOD status when integer is used
  addons/radar/functions/fnc_getIcon.sqf
Labels: bug

#175 Add setting to show dui during dialogs
  addons/main/XEH_preInit.sqf
  addons/main/functions/fnc_canHudBeShown.sqf
  addons/main/stringtable.xml
Labels: enhancement

#174 Add setting for Bearing outline
  .gitattributes
  addons/main/stringtable.xml
  addons/radar/XEH_preInit.sqf
  addons/radar/functions/fnc_compassPFH.sqf
Labels: enhancement

#176 Add consolidated support for custom names
  addons/nametags/functions/fnc_cacheLoop.sqf
  addons/nametags/functions/fnc_onDraw.sqf
  addons/radar/functions/fnc_cacheLoop.sqf
  addons/radar/functions/fnc_sortNameList.sqf
Labels: enhancement

#177 Add setting to show bearing only as driver of vehicle
  addons/main/stringtable.xml
  addons/radar/XEH_preInit.sqf
  addons/radar/functions/fnc_compassPFH.sqf
Labels: enhancement

#178 use compileScript instead of preprocessFileLineNumbers
  addons/main/script_macros.hpp
  include/x/cba/addons/main/script_macros_common.hpp
Labels: ignore_changelog
