Repository diwako/diwako_dui, pull requests merged in 2021-05, with the labels that each got.

#186 Radar - Add an option to show bearing only if the player has a GPS
  addons/main/stringtable.xml
  addons/radar/XEH_PREP.hpp
  addons/radar/XEH_preInit.sqf
  addons/radar/functions/fnc_compassPFH.sqf
  addons/radar/functions/fnc_getCompass.sqf
  addons/radar/functions/fnc_getGPS.sqf
Labels: enhancement

#190 Fixed nametag display inconsistency
  addons/nametags/functions/fnc_onDraw.sqf
Labels: enhancement

#191 Radar - Added setting to change priority for icons
  addons/main/stringtable.xml
  addons/radar/XEH_preInit.sqf
  addons/radar/functions/fnc_getIcon.sqf
Labels: enhancement

#192 Further prep for sqfc
  .editorconfig
  .gitattributes
  .gitignore
  addons/buddy/XEH_PREP.hpp
  addons/buddy/config.cpp
  addons/buddy/stringtable.xml
  addons/main/CfgIconStyles.hpp
  addons/nametags/functions/fnc_onDraw.sqf
  addons/radar/CfgPointerStyles.hpp
  addons/radar/XEH_preInit.sqf
  addons/radar/functions/fnc_compassPFH.sqf
  addons/radar/functions/fnc_syncGroups.sqf
  addons/radar/functions/script_component.hpp
Labels: ignore_changelog

#193 Fix incorrect blue color on radar for diwako_dui_colors >> tritanomaly
  addons/main/CfgColorStyles.hpp
  addons/main/include/getColorStyles.sqf
Labels: bug
